export const DATABASE = {
  stocks: [
    {
      ticker: "EMIM LN ETF",
      quantity: 35,
      currentPrice: 27.57,
      currency: "GBP",
      averagePurchasePrice: 27.35,
      walletId: 1,
    },
    {
      ticker: "SGLN LN ETF",
      quantity: 40,
      currentPrice: 27.09,
      currency: "GBP",
      averagePurchasePrice: 24.03,
      walletId: 1,
    },
    {
      ticker: 'ALIBABA GROUP HLDG ADR',
      quantity: 20,
      currentPrice: 168.43,
      currency: 'USD',
      averagePurchasePrice: 156.2350,
      walletId: 1,
    },
    {
      ticker: "EMIM LN ETF",
      quantity: 35,
      currentPrice: 27.57,
      currency: "GBP",
      averagePurchasePrice: 27.35,
      walletId: 2,
    },
    {
      ticker: "SGLN LN ETF",
      quantity: 40,
      currentPrice: 27.09,
      currency: "GBP",
      averagePurchasePrice: 24.03,
      walletId: 2,
    },
    {
      ticker: 'ALIBABA GROUP HLDG ADR',
      quantity: 20,
      currentPrice: 168.43,
      currency: 'USD',
      averagePurchasePrice: 156.2350,
      walletId: 2,
    },
    {
      ticker: "EMIM LN ETF",
      quantity: 35,
      currentPrice: 27.57,
      currency: "GBP",
      averagePurchasePrice: 27.35,
      walletId: 3,
    },
    {
      ticker: "SGLN LN ETF",
      quantity: 40,
      currentPrice: 27.09,
      currency: "GBP",
      averagePurchasePrice: 24.03,
      walletId: 3,
    },
    {
      ticker: 'ALIBABA GROUP HLDG ADR',
      quantity: 20,
      currentPrice: 168.43,
      currency: 'USD',
      averagePurchasePrice: 156.2350,
      walletId: 3,
    },
    {
      ticker: "EMIM LN ETF",
      quantity: 35,
      currentPrice: 27.57,
      currency: "GBP",
      averagePurchasePrice: 27.35,
      walletId: 4,
    },
    {
      ticker: "SGLN LN ETF",
      quantity: 40,
      currentPrice: 27.09,
      currency: "GBP",
      averagePurchasePrice: 24.03,
      walletId: 4,
    },
    {
      ticker: 'ALIBABA GROUP HLDG ADR',
      quantity: 20,
      currentPrice: 168.43,
      currency: 'USD',
      averagePurchasePrice: 156.2350,
      walletId: 4,
    },
    {
      ticker: "EMIM LN ETF",
      quantity: 35,
      currentPrice: 27.57,
      currency: "GBP",
      averagePurchasePrice: 27.35,
      walletId: 1,
    },
    {
      ticker: "SGLN LN ETF",
      quantity: 40,
      currentPrice: 27.09,
      currency: "GBP",
      averagePurchasePrice: 24.03,
      walletId: 2,
    },
    {
      ticker: 'ALIBABA GROUP HLDG ADR',
      quantity: 20,
      currentPrice: 168.43,
      currency: 'USD',
      averagePurchasePrice: 156.2350,
      walletId: 1,
    },
    {
      ticker: "EMIM LN ETF",
      quantity: 35,
      currentPrice: 27.57,
      currency: "GBP",
      averagePurchasePrice: 27.35,
      walletId: 2,
    },
    {
      ticker: "SGLN LN ETF",
      quantity: 40,
      currentPrice: 27.09,
      currency: "GBP",
      averagePurchasePrice: 24.03,
      walletId: 2,
    },
    {
      ticker: 'ALIBABA GROUP HLDG ADR',
      quantity: 20,
      currentPrice: 168.43,
      currency: 'USD',
      averagePurchasePrice: 156.2350,
      walletId: 4,
    },
    {
      ticker: "EMIM LN ETF",
      quantity: 35,
      currentPrice: 27.57,
      currency: "GBP",
      averagePurchasePrice: 27.35,
      walletId: 2,
    },
    {
      ticker: "SGLN LN ETF",
      quantity: 40,
      currentPrice: 27.09,
      currency: "GBP",
      averagePurchasePrice: 24.03,
      walletId: 3,
    },
    {
      ticker: 'ALIBABA GROUP HLDG ADR',
      quantity: 20,
      currentPrice: 168.43,
      currency: 'USD',
      averagePurchasePrice: 156.2350,
      walletId: 4,
    },
  ],
  wallets: [
    { key: 1, label: 'Retirement' },
    { key: 2, label: 'Longterm' },
    { key: 3, label: 'Speculative' },
    { key: 4, label: 'Model' },
  ]
};
